### ISSUE TITLE
minor friction when using hakyll+nix in configuration.nix

### ISSUE THREAD

**Issue by shapr** [rpearce/robertwpearce.com#136]
https://github.com/rpearce/robertwpearce.com/blob/655e73dba475dea2816c0cf63896ec0fc5a9dde5/flake.nix#L76

This might be the wrong place to report this bug?

I wanted to use your hakyll+nix blog builder in my configuration.nix
I spent fruitless hours debugging, and finally discovered that I had to manually add `/dist/` as shown here:

https://github.com/shapr/surtr/blob/main/surtr.nix#L71

Would you be open to a pull request changing the output directory to `$out` ?

**Comment by rpearce** [comment]
@shapr It's been quite a while since I've thought about this, but if I recall correctly, the GitHub CI artifact builder used had a bug that required there to be a directory at this level. Something rings a bell that the issue was fixed a year or two later, but it's not been something I've had a problem with.

I'm terribly sorry you ran into an issue that sucked up that much time :(

Given I think the way I have this set up in the hakyll-nix-template it _should_ work, I wouldn't worry about a PR, but I am so grateful for your offer.
